#Service v1
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    env: dev
  namespace: dev
spec:
  selector:
    env: dev
  type: NodePort
  ports:
    - name: svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000