apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    env: dev
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - name: mysql-port
          contaienrPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "avinash"
        - name: MYSQL_PASSWORD
          value: "avinash123"
        - name: MYSQL_DATABASE
          value: "student_db"
