apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    env: dev
spec:
  containers:
    - name: tomcat-cont
      image: tomcat:latest
      ports:
        - name: tomcat-port
          containerPort: 8080
          