#Secret v1
apiVersion: v1
kind: Secret
metadata:
  name: my-sec
  labels:
    env: dev
data:
  #encoding this using 
  # echo -n "root" | base64
  #decoding this using
  # echo -n "cm9vdA==" | base64 --decode oR echo "cm9vdA==" | base64 --decode
  mysql_root_password: cm9vdA==