#StatefulSet apps/v1
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
  labels:
    env: dev
spec:
  replicas: 10
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: mysql-cont
          image: mysql:8.0
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-cfg
                  key: mysql_root_password
                  
              
